<?php
/**
 * HolidayEntitlementApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PeopleHR API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * Contact: customerservices@peoplehr.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * HolidayEntitlementApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HolidayEntitlementApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'holidayEntitlementGetHolidayEntitlementPost' => [
            'application/json',
        ],
        'holidayEntitlementGetNextYearHolidayEntitlementPost' => [
            'application/json',
        ],
        'holidayEntitlementUpdateHolidayEntitlementPost' => [
            'application/json',
        ],
        'holidayEntitlementUpdateNextYearHolidayEntitlementPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation holidayEntitlementGetHolidayEntitlementPost
     *
     * Get Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetHolidayEntitlementParameter $body body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ErrorForGetHolidayEntitlement
     */
    public function holidayEntitlementGetHolidayEntitlementPost($body, string $contentType = self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'][0])
    {
        list($response) = $this->holidayEntitlementGetHolidayEntitlementPostWithHttpInfo($body, $contentType);
        return $response;
    }

    /**
     * Operation holidayEntitlementGetHolidayEntitlementPostWithHttpInfo
     *
     * Get Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ErrorForGetHolidayEntitlement, HTTP status code, HTTP response headers (array of strings)
     */
    public function holidayEntitlementGetHolidayEntitlementPostWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'][0])
    {
        $request = $this->holidayEntitlementGetHolidayEntitlementPostRequest($body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ErrorForGetHolidayEntitlement' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ErrorForGetHolidayEntitlement' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ErrorForGetHolidayEntitlement', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ErrorForGetHolidayEntitlement';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ErrorForGetHolidayEntitlement',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation holidayEntitlementGetHolidayEntitlementPostAsync
     *
     * Get Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementGetHolidayEntitlementPostAsync($body, string $contentType = self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'][0])
    {
        return $this->holidayEntitlementGetHolidayEntitlementPostAsyncWithHttpInfo($body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation holidayEntitlementGetHolidayEntitlementPostAsyncWithHttpInfo
     *
     * Get Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementGetHolidayEntitlementPostAsyncWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ErrorForGetHolidayEntitlement';
        $request = $this->holidayEntitlementGetHolidayEntitlementPostRequest($body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'holidayEntitlementGetHolidayEntitlementPost'
     *
     * @param  \OpenAPI\Client\Model\GetHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function holidayEntitlementGetHolidayEntitlementPostRequest($body, string $contentType = self::contentTypes['holidayEntitlementGetHolidayEntitlementPost'][0])
    {

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling holidayEntitlementGetHolidayEntitlementPost'
            );
        }


        $resourcePath = '/Holiday Entitlement  -  GetHolidayEntitlement';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation holidayEntitlementGetNextYearHolidayEntitlementPost
     *
     * Get Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetNextYearHolidayEntitlementParameter $body body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement
     */
    public function holidayEntitlementGetNextYearHolidayEntitlementPost($body, string $contentType = self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'][0])
    {
        list($response) = $this->holidayEntitlementGetNextYearHolidayEntitlementPostWithHttpInfo($body, $contentType);
        return $response;
    }

    /**
     * Operation holidayEntitlementGetNextYearHolidayEntitlementPostWithHttpInfo
     *
     * Get Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement, HTTP status code, HTTP response headers (array of strings)
     */
    public function holidayEntitlementGetNextYearHolidayEntitlementPostWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'][0])
    {
        $request = $this->holidayEntitlementGetNextYearHolidayEntitlementPostRequest($body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation holidayEntitlementGetNextYearHolidayEntitlementPostAsync
     *
     * Get Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementGetNextYearHolidayEntitlementPostAsync($body, string $contentType = self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'][0])
    {
        return $this->holidayEntitlementGetNextYearHolidayEntitlementPostAsyncWithHttpInfo($body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation holidayEntitlementGetNextYearHolidayEntitlementPostAsyncWithHttpInfo
     *
     * Get Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\GetNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementGetNextYearHolidayEntitlementPostAsyncWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ErrorForGetNextYearHolidayEntitlement';
        $request = $this->holidayEntitlementGetNextYearHolidayEntitlementPostRequest($body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'holidayEntitlementGetNextYearHolidayEntitlementPost'
     *
     * @param  \OpenAPI\Client\Model\GetNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function holidayEntitlementGetNextYearHolidayEntitlementPostRequest($body, string $contentType = self::contentTypes['holidayEntitlementGetNextYearHolidayEntitlementPost'][0])
    {

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling holidayEntitlementGetNextYearHolidayEntitlementPost'
            );
        }


        $resourcePath = '/Holiday Entitlement  -  GetNextYearHolidayEntitlement';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation holidayEntitlementUpdateHolidayEntitlementPost
     *
     * Update Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateHolidayEntitlementParameter $body body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement
     */
    public function holidayEntitlementUpdateHolidayEntitlementPost($body, string $contentType = self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'][0])
    {
        list($response) = $this->holidayEntitlementUpdateHolidayEntitlementPostWithHttpInfo($body, $contentType);
        return $response;
    }

    /**
     * Operation holidayEntitlementUpdateHolidayEntitlementPostWithHttpInfo
     *
     * Update Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement, HTTP status code, HTTP response headers (array of strings)
     */
    public function holidayEntitlementUpdateHolidayEntitlementPostWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'][0])
    {
        $request = $this->holidayEntitlementUpdateHolidayEntitlementPostRequest($body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation holidayEntitlementUpdateHolidayEntitlementPostAsync
     *
     * Update Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementUpdateHolidayEntitlementPostAsync($body, string $contentType = self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'][0])
    {
        return $this->holidayEntitlementUpdateHolidayEntitlementPostAsyncWithHttpInfo($body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation holidayEntitlementUpdateHolidayEntitlementPostAsyncWithHttpInfo
     *
     * Update Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementUpdateHolidayEntitlementPostAsyncWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ErrorForUpdateHolidayEntitlement';
        $request = $this->holidayEntitlementUpdateHolidayEntitlementPostRequest($body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'holidayEntitlementUpdateHolidayEntitlementPost'
     *
     * @param  \OpenAPI\Client\Model\UpdateHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function holidayEntitlementUpdateHolidayEntitlementPostRequest($body, string $contentType = self::contentTypes['holidayEntitlementUpdateHolidayEntitlementPost'][0])
    {

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling holidayEntitlementUpdateHolidayEntitlementPost'
            );
        }


        $resourcePath = '/Holiday Entitlement  -  UpdateHolidayEntitlement';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation holidayEntitlementUpdateNextYearHolidayEntitlementPost
     *
     * Update Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateNextYearHolidayEntitlementParameter $body body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement
     */
    public function holidayEntitlementUpdateNextYearHolidayEntitlementPost($body, string $contentType = self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'][0])
    {
        list($response) = $this->holidayEntitlementUpdateNextYearHolidayEntitlementPostWithHttpInfo($body, $contentType);
        return $response;
    }

    /**
     * Operation holidayEntitlementUpdateNextYearHolidayEntitlementPostWithHttpInfo
     *
     * Update Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement, HTTP status code, HTTP response headers (array of strings)
     */
    public function holidayEntitlementUpdateNextYearHolidayEntitlementPostWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'][0])
    {
        $request = $this->holidayEntitlementUpdateNextYearHolidayEntitlementPostRequest($body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation holidayEntitlementUpdateNextYearHolidayEntitlementPostAsync
     *
     * Update Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementUpdateNextYearHolidayEntitlementPostAsync($body, string $contentType = self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'][0])
    {
        return $this->holidayEntitlementUpdateNextYearHolidayEntitlementPostAsyncWithHttpInfo($body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation holidayEntitlementUpdateNextYearHolidayEntitlementPostAsyncWithHttpInfo
     *
     * Update Next Year Holiday Entitlement
     *
     * @param  \OpenAPI\Client\Model\UpdateNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function holidayEntitlementUpdateNextYearHolidayEntitlementPostAsyncWithHttpInfo($body, string $contentType = self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ErrorForUpdateNextYearHolidayEntitlement';
        $request = $this->holidayEntitlementUpdateNextYearHolidayEntitlementPostRequest($body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'holidayEntitlementUpdateNextYearHolidayEntitlementPost'
     *
     * @param  \OpenAPI\Client\Model\UpdateNextYearHolidayEntitlementParameter $body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function holidayEntitlementUpdateNextYearHolidayEntitlementPostRequest($body, string $contentType = self::contentTypes['holidayEntitlementUpdateNextYearHolidayEntitlementPost'][0])
    {

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling holidayEntitlementUpdateNextYearHolidayEntitlementPost'
            );
        }


        $resourcePath = '/Holiday Entitlement  -  UpdateNextYearHolidayEntitlement';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
