<?php
/**
 * Result1GetHolidayDetailArrayInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PeopleHR API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1
 * Contact: customerservices@peoplehr.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Result1GetHolidayDetailArrayInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Result1GetHolidayDetailArrayInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Result1GetHolidayDetailArray_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'start_date' => '\DateTime',
        'end_date' => '\DateTime',
        'duration_type' => 'int',
        'duration_in_days' => 'int',
        'duration_in_minutes' => 'int',
        'duration_in_days_this_period' => 'int',
        'duration_in_minutes_this_period' => 'int',
        'part_of_day' => 'string',
        'requester_comments' => 'string',
        'approver_comments' => 'string',
        'approver' => 'string',
        'status' => 'string',
        'last_action_date_time' => 'string',
        'is_toil_holiday' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'start_date' => 'date',
        'end_date' => 'date',
        'duration_type' => null,
        'duration_in_days' => 'decimal',
        'duration_in_minutes' => null,
        'duration_in_days_this_period' => 'decimal',
        'duration_in_minutes_this_period' => null,
        'part_of_day' => null,
        'requester_comments' => null,
        'approver_comments' => null,
        'approver' => null,
        'status' => null,
        'last_action_date_time' => 'datetime',
        'is_toil_holiday' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'start_date' => false,
        'end_date' => false,
        'duration_type' => false,
        'duration_in_days' => false,
        'duration_in_minutes' => false,
        'duration_in_days_this_period' => false,
        'duration_in_minutes_this_period' => false,
        'part_of_day' => false,
        'requester_comments' => false,
        'approver_comments' => false,
        'approver' => false,
        'status' => false,
        'last_action_date_time' => false,
        'is_toil_holiday' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'start_date' => 'StartDate',
        'end_date' => 'EndDate',
        'duration_type' => 'DurationType',
        'duration_in_days' => 'DurationInDays',
        'duration_in_minutes' => 'DurationInMinutes',
        'duration_in_days_this_period' => 'DurationInDaysThisPeriod',
        'duration_in_minutes_this_period' => 'DurationInMinutesThisPeriod',
        'part_of_day' => 'PartOfDay',
        'requester_comments' => 'RequesterComments',
        'approver_comments' => 'ApproverComments',
        'approver' => 'Approver',
        'status' => 'Status',
        'last_action_date_time' => 'LastActionDateTime',
        'is_toil_holiday' => 'IsToilHoliday'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'start_date' => 'setStartDate',
        'end_date' => 'setEndDate',
        'duration_type' => 'setDurationType',
        'duration_in_days' => 'setDurationInDays',
        'duration_in_minutes' => 'setDurationInMinutes',
        'duration_in_days_this_period' => 'setDurationInDaysThisPeriod',
        'duration_in_minutes_this_period' => 'setDurationInMinutesThisPeriod',
        'part_of_day' => 'setPartOfDay',
        'requester_comments' => 'setRequesterComments',
        'approver_comments' => 'setApproverComments',
        'approver' => 'setApprover',
        'status' => 'setStatus',
        'last_action_date_time' => 'setLastActionDateTime',
        'is_toil_holiday' => 'setIsToilHoliday'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'start_date' => 'getStartDate',
        'end_date' => 'getEndDate',
        'duration_type' => 'getDurationType',
        'duration_in_days' => 'getDurationInDays',
        'duration_in_minutes' => 'getDurationInMinutes',
        'duration_in_days_this_period' => 'getDurationInDaysThisPeriod',
        'duration_in_minutes_this_period' => 'getDurationInMinutesThisPeriod',
        'part_of_day' => 'getPartOfDay',
        'requester_comments' => 'getRequesterComments',
        'approver_comments' => 'getApproverComments',
        'approver' => 'getApprover',
        'status' => 'getStatus',
        'last_action_date_time' => 'getLastActionDateTime',
        'is_toil_holiday' => 'getIsToilHoliday'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PART_OF_DAY_AM = 'AM';
    public const PART_OF_DAY_PM = 'PM';
    public const STATUS_SUBMITTED = 'Submitted';
    public const STATUS_APPROVED = 'Approved';
    public const STATUS_REJECTED = 'Rejected';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPartOfDayAllowableValues()
    {
        return [
            self::PART_OF_DAY_AM,
            self::PART_OF_DAY_PM,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_SUBMITTED,
            self::STATUS_APPROVED,
            self::STATUS_REJECTED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('end_date', $data ?? [], null);
        $this->setIfExists('duration_type', $data ?? [], null);
        $this->setIfExists('duration_in_days', $data ?? [], null);
        $this->setIfExists('duration_in_minutes', $data ?? [], null);
        $this->setIfExists('duration_in_days_this_period', $data ?? [], null);
        $this->setIfExists('duration_in_minutes_this_period', $data ?? [], null);
        $this->setIfExists('part_of_day', $data ?? [], null);
        $this->setIfExists('requester_comments', $data ?? [], null);
        $this->setIfExists('approver_comments', $data ?? [], null);
        $this->setIfExists('approver', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('last_action_date_time', $data ?? [], null);
        $this->setIfExists('is_toil_holiday', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPartOfDayAllowableValues();
        if (!is_null($this->container['part_of_day']) && !in_array($this->container['part_of_day'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'part_of_day', must be one of '%s'",
                $this->container['part_of_day'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets start_date
     *
     * @return \DateTime|null
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime|null $start_date Start date value
     *
     * @return self
     */
    public function setStartDate($start_date)
    {
        if (is_null($start_date)) {
            throw new \InvalidArgumentException('non-nullable start_date cannot be null');
        }
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return \DateTime|null
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param \DateTime|null $end_date End date value
     *
     * @return self
     */
    public function setEndDate($end_date)
    {
        if (is_null($end_date)) {
            throw new \InvalidArgumentException('non-nullable end_date cannot be null');
        }
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets duration_type
     *
     * @return int|null
     */
    public function getDurationType()
    {
        return $this->container['duration_type'];
    }

    /**
     * Sets duration_type
     *
     * @param int|null $duration_type DurationType value
     *
     * @return self
     */
    public function setDurationType($duration_type)
    {
        if (is_null($duration_type)) {
            throw new \InvalidArgumentException('non-nullable duration_type cannot be null');
        }
        $this->container['duration_type'] = $duration_type;

        return $this;
    }

    /**
     * Gets duration_in_days
     *
     * @return int|null
     */
    public function getDurationInDays()
    {
        return $this->container['duration_in_days'];
    }

    /**
     * Sets duration_in_days
     *
     * @param int|null $duration_in_days DurationInDays value
     *
     * @return self
     */
    public function setDurationInDays($duration_in_days)
    {
        if (is_null($duration_in_days)) {
            throw new \InvalidArgumentException('non-nullable duration_in_days cannot be null');
        }
        $this->container['duration_in_days'] = $duration_in_days;

        return $this;
    }

    /**
     * Gets duration_in_minutes
     *
     * @return int|null
     */
    public function getDurationInMinutes()
    {
        return $this->container['duration_in_minutes'];
    }

    /**
     * Sets duration_in_minutes
     *
     * @param int|null $duration_in_minutes DurationInMinutes value
     *
     * @return self
     */
    public function setDurationInMinutes($duration_in_minutes)
    {
        if (is_null($duration_in_minutes)) {
            throw new \InvalidArgumentException('non-nullable duration_in_minutes cannot be null');
        }
        $this->container['duration_in_minutes'] = $duration_in_minutes;

        return $this;
    }

    /**
     * Gets duration_in_days_this_period
     *
     * @return int|null
     */
    public function getDurationInDaysThisPeriod()
    {
        return $this->container['duration_in_days_this_period'];
    }

    /**
     * Sets duration_in_days_this_period
     *
     * @param int|null $duration_in_days_this_period DurationInDaysThisPeriod value
     *
     * @return self
     */
    public function setDurationInDaysThisPeriod($duration_in_days_this_period)
    {
        if (is_null($duration_in_days_this_period)) {
            throw new \InvalidArgumentException('non-nullable duration_in_days_this_period cannot be null');
        }
        $this->container['duration_in_days_this_period'] = $duration_in_days_this_period;

        return $this;
    }

    /**
     * Gets duration_in_minutes_this_period
     *
     * @return int|null
     */
    public function getDurationInMinutesThisPeriod()
    {
        return $this->container['duration_in_minutes_this_period'];
    }

    /**
     * Sets duration_in_minutes_this_period
     *
     * @param int|null $duration_in_minutes_this_period DurationInMinutesThisPeriod value
     *
     * @return self
     */
    public function setDurationInMinutesThisPeriod($duration_in_minutes_this_period)
    {
        if (is_null($duration_in_minutes_this_period)) {
            throw new \InvalidArgumentException('non-nullable duration_in_minutes_this_period cannot be null');
        }
        $this->container['duration_in_minutes_this_period'] = $duration_in_minutes_this_period;

        return $this;
    }

    /**
     * Gets part_of_day
     *
     * @return string|null
     */
    public function getPartOfDay()
    {
        return $this->container['part_of_day'];
    }

    /**
     * Sets part_of_day
     *
     * @param string|null $part_of_day PartOfDay value
     *
     * @return self
     */
    public function setPartOfDay($part_of_day)
    {
        if (is_null($part_of_day)) {
            throw new \InvalidArgumentException('non-nullable part_of_day cannot be null');
        }
        $allowedValues = $this->getPartOfDayAllowableValues();
        if (!in_array($part_of_day, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'part_of_day', must be one of '%s'",
                    $part_of_day,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['part_of_day'] = $part_of_day;

        return $this;
    }

    /**
     * Gets requester_comments
     *
     * @return string|null
     */
    public function getRequesterComments()
    {
        return $this->container['requester_comments'];
    }

    /**
     * Sets requester_comments
     *
     * @param string|null $requester_comments RequesterComments value
     *
     * @return self
     */
    public function setRequesterComments($requester_comments)
    {
        if (is_null($requester_comments)) {
            throw new \InvalidArgumentException('non-nullable requester_comments cannot be null');
        }
        $this->container['requester_comments'] = $requester_comments;

        return $this;
    }

    /**
     * Gets approver_comments
     *
     * @return string|null
     */
    public function getApproverComments()
    {
        return $this->container['approver_comments'];
    }

    /**
     * Sets approver_comments
     *
     * @param string|null $approver_comments ApproverComments value
     *
     * @return self
     */
    public function setApproverComments($approver_comments)
    {
        if (is_null($approver_comments)) {
            throw new \InvalidArgumentException('non-nullable approver_comments cannot be null');
        }
        $this->container['approver_comments'] = $approver_comments;

        return $this;
    }

    /**
     * Gets approver
     *
     * @return string|null
     */
    public function getApprover()
    {
        return $this->container['approver'];
    }

    /**
     * Sets approver
     *
     * @param string|null $approver Approver value
     *
     * @return self
     */
    public function setApprover($approver)
    {
        if (is_null($approver)) {
            throw new \InvalidArgumentException('non-nullable approver cannot be null');
        }
        $this->container['approver'] = $approver;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Status value
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets last_action_date_time
     *
     * @return string|null
     */
    public function getLastActionDateTime()
    {
        return $this->container['last_action_date_time'];
    }

    /**
     * Sets last_action_date_time
     *
     * @param string|null $last_action_date_time LastActionDateTime value
     *
     * @return self
     */
    public function setLastActionDateTime($last_action_date_time)
    {
        if (is_null($last_action_date_time)) {
            throw new \InvalidArgumentException('non-nullable last_action_date_time cannot be null');
        }
        $this->container['last_action_date_time'] = $last_action_date_time;

        return $this;
    }

    /**
     * Gets is_toil_holiday
     *
     * @return bool|null
     */
    public function getIsToilHoliday()
    {
        return $this->container['is_toil_holiday'];
    }

    /**
     * Sets is_toil_holiday
     *
     * @param bool|null $is_toil_holiday IsToilHoliday value
     *
     * @return self
     */
    public function setIsToilHoliday($is_toil_holiday)
    {
        if (is_null($is_toil_holiday)) {
            throw new \InvalidArgumentException('non-nullable is_toil_holiday cannot be null');
        }
        $this->container['is_toil_holiday'] = $is_toil_holiday;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


